### ISSUE TITLE
Cookies store url-encoded column character in URLs

### ISSUE THREAD

**Issue by ErinPo** [medius/utm_form#11]
There seems to be a bug causing the values for initial landing page, initial referrer and last referrer to be stored as https%3A//www.domain.com instead of https://www.domain.com.

**Comment by medius** [comment]
Yes, any values saved in the cookies are URL encoded. This is to make sure that the cookie value does not contain any semicolon, comma, whitespace, etc. which are disallowed in cookie values.

It's possible to decode the values before setting them in the form. Mind issuing a PR for that?

**Comment by ErinPo** [comment]
Wouldn't URL encoding be modifying slashes as well? Your code only modifies the column character in URLs.

**Comment by rob** [comment]
@medius - did you stop working on this project? I fixed this issue.

I modified the script to include a `_uf.decode_uris = true;` option (set to false by default to be backwards-compatible) that fixes this using `decodeURIComponent`. I could submit a pull request if you'd like.

**Comment by medius** [comment]
@rob Sorry about that. I'll try to carve out more time for this project, but am definitely accepting pull requests.

Please submit one if you have something ready. I'll be glad to review and merge.

**Comment by rob** [comment]
@medius will do this week - sorry, my day job takes up most of my time right now. :)

Do you think it should be an option like I showed, or just something that's done by default?

**Comment by medius** [comment]
@rob I completely understand. No hurry.

By default the script writes `document.referrer` in the cookie without explicit encoding or other modification. So I think it's better to have an explicit option to enable decoding. This will not only maintain backward compatibility, but any side effects will then be responsibility of the user setting this option.

**Comment by rob** [comment]
@medius I submitted two PRs - #15 and #16 :)

**Comment by medius** [comment]
@rob Thanks, I'll review them asap, hopefully within a day or two.

**Comment by medius** [comment]
@rob This is now available via CDN as well https://d12ue6f2329cfl.cloudfront.net/resources/utm_form-1.1.0.min.js

Thanks for your contribution. I really appreciate it. I'll close this issue.
