### ISSUE TITLE
Support hash-mode routers

### ISSUE THREAD

**Issue by tejasbubane** [medius/utm_form#13]
React and Vue routers by default use `hash-mode` which generate URLs like http://example.com/#/signup?utm_medium=sample

`window.location.search` is [used here](https://github.com/medius/utm_form/blob/master/lib/utm_cookie.coffee#L64) to find the search params which is empty string in case of these kind of URLs. Hence passing params in such URLs does not set them in forms.

 Can we please support the hash URLs as well?

**Comment by medius** [comment]
The recommended and most common Google Analytics setup uses query UTM parameters. This is a rare case and will only cause confusion for most people.
