### ISSUE TITLE
Support for Mailchimp's subscriber pop-up?

### ISSUE THREAD

**Issue by timbremer** [medius/utm_form#14]
Hi! I've been trying hard to add UTM information about subscribers to my list, but without luck so far. Your script was a great lead, but the problem is be that we are using Mailchimp's popup generator, which works via iframes. Is there any way to track the parameters with the subscriber pop-up?

**Comment by medius** [comment]
@timbremer Sorry for the late reply. Yes, the iframe makes it difficult to work with because it's not possible (as far as I know) to inject a script tag into an iframe. I've not been able to commit enough time to try to fix this scenario. If you have any ideas, I'll definitely look at it closely.

**Comment by medius** [comment]
Closing this issue since there's no obvious easy solution yet. If anyone has a solution, please open another issue along with your recommended approach.
