### ISSUE TITLE
HTTP_REFERRER contains utm_* parameters, but added form fields is empty

### ISSUE THREAD

**Issue by TooLogic** [medius/utm_form#17]
In my case I check HTTP_REFERRER server globals and USOURCE...UCONTENT parameters in post function. And although HTTP_REFERRER contains url with utm tags, in the corresponding  form fields these values are empty (value="null") . How does this happen?

**Comment by medius** [comment]
The script doesn't use HTTP_REFERRER, but the current url in the browser using javascript. The referrer is for where the visitor came from and not the url they clicked.

It's not possible to debug specific cases here. Please reopen the issue if you can provide specific example that explains in detail how the behavior is deviating from expectation.
