### ISSUE TITLE
Last parameters are inherited

### ISSUE THREAD

**Issue by gioamato** [medius/utm_form#19]
Noticed just now that the utm and additional last parameters are not true but inherited. E.g.:

Visit 1: utm_parameter=1
            cookie value = 1
            form value = 1

Visit 2: utm_parameter=2
            cookie value = 2
            form value = 2

Visit 3: utm_parameter missing
            cookie value = 2 (inherited)
            form value = 2 (inherited)

This is caused by the check `if (this.utmPresentInUrl())` inside the `UtmCookie` class constructor. Same applies to additional parameters because of `if (this.additionalParamsPresentInUrl())`.

Should the condition be removed? So the utm and additional last parameters will be null if not present and the resulting data will be more consistent. Otherwise an option to track last values can be added and if true it will write utm and additional last parameters with null values if not present inside the URL.

@medius what do you think about that?

**Comment by gioamato** [comment]
Added in #20 alongside an option to set the desired behavior.

**Comment by medius** [comment]
One of the features of this script is that the UTM parameters are tracked and filled correctly when a visitor lands on the website, navigates around and then fills a form. Writing UTM (and other) parameters only when they are present achieves this purpose. 

Visit 3: utm_parameter missing
cookie value = 2 (inherited)
form value = 2 (inherited)

After Visit 3 (which could just be a navigation within the website), the UTMs will be gone if set to null. We want the values from Visit 2 to be used.

It might be good to track the initial UTM parameters, but the last UTM parameters could still be maintained. Having a separate option to enable this might be confusing. It seems `track_last_params` will break this but it seems to convey the opposite.

@gioamato Do you agree with this?

**Comment by gioamato** [comment]
You are absolutely right. Maybe for 90% of cases. But i've got this business requirement to track the latest parameters changes, even if null. I could have done the personalization for myself but i decided to do "more work" and left it open source, maybe it can help someone.

So i went for the option to personalize script behaviour and i will also add a check for current session, so the value will be kept if the user navigates the website until a new session, resulting in more consistent data.

I convey with you about the confusing option name. @medius have you any naming suggestion?

**Comment by gioamato** [comment]
Discussion moved in #20
