### ISSUE TITLE
Case sensitive to UTM names in URL

### ISSUE THREAD

**Issue by erikdkennedy** [medius/utm_form#8]
I noticed that when I try from a URL with "UTM_SOURCE=foo", the form does not populate with the UTM Source parameter. However, when the URL has a lowercase property – "utm_source=foo" – then it does.

**Comment by medius** [comment]
Do you know how Google Analytics (and other analytics tools) look at these non-lower case UTM parameters? I haven't tested such cases so I'm not sure. Just want to make sure supporting other cases makes sense or not.

**Comment by medius** [comment]
Since this is a rare case and not really in demand, I'm closing this issue.
