### ISSUE TITLE
Default session length and cookie expiry to match Google Analytics

### ISSUE THREAD

**Issue by ErinPo** [medius/utm_form#9]
Shouldn't the default session length and cookie expiry match the defaults in Google Analytics (30 min and 2 years)? 

utm_form defaults to 1 hour and 1 year.

What do you think?

**Comment by medius** [comment]
Even though Google Analytics is quite popular, the script is meant to be used with any analytics/CRM tools. But it's possible that these are kept in sync with GA.

How about issuing a PR for this change?

**Comment by ErinPo** [comment]
The thing is I am not a developer and I don't currently have the time to learn how to use Github, especially just for making such a small contribution:(

**Comment by medius** [comment]
Session length is configurable using _uf.sessionLength
